pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Validate Skeleton') {
      steps {
        sh 'sh ./scripts/validate.sh'
      }
    }
  }
}
