services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /srv/jenkins/home:/var/jenkins_home
    restart: unless-stopped